/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a4f6dd6d-e17f-449a-9f5c-4871bfd3c899",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8bOz9a3Cn",
    "aws_user_pools_web_client_id": "18qco33o2ootpjg8kj2al0tk8h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t4nmg5qhnvfsbgyh46plrgs3yq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vt2qbqw4mjebjmohvg5hak4rnm"
};


export default awsmobile;
